### ISSUE TITLE
2021.04.12 월 review

### ISSUE THREAD

**Issue by sejun09** [sejun09/E-oN#17]
# 5월달 목표 

1. 신호등 교통 시스템 이해  -----> 윤설, 주하 
2. openCV공부  -----> 세준, 세빈

**각자 공부(조사)한거 github에 정리해서 올려두기**
**카톡방에 공유된 openCV강의 how to build opencv, ceemple, webcam example까지 강의 듣기 (5/3일 전까지)**

------------------------------
### 5/3일 offline meeting(예정)

- 각자 공부(조사)한 것 공유
- 도시교통공학과 교수님 면담

이 후 한이음 멘토님이랑 회의

**Comment by choyunseol** [comment]
확인했습니다
