### ISSUE TITLE
after review meeting 2021.03.18 목

### ISSUE THREAD

**Issue by sejun09** [sejun09/E-oN#4]
### 드론 택배함, 빨래 구분 장치

- 이전 3가지 아이디어중 드론택배함 선정  
- 추가 아이디어 빨래를 구분하는 장치 

**객관적 증거, 구체성, 상업성 3가지를 중점으로 조사하여  다시 회의 하기**
   

> 택배함 세준, 윤설 

 
>  빨래 구분 장치 세빈, 주하

  

- 두 가지 아이디어에 대해 구체화 시킨 후 그 분야와 맞는 교수님께 찾아가서 조언 구하기 

### 다음 회의 일정 

- 3/20 (토) 21:30분 google meeting    <- 조사한것 토대로 회의 

- 3/22 (월) 21:30분 google meeting    <- 아이디어에 대해 일부분 구체화? 시키기 

- 3월 25 or 26일 중 교수님 방문하여 조언 구하기

**Comment by choyunseol** [comment]
- 3/22 (월) meeting 23:00 으로 변경

* 이하는 3/18 meeting에 앞서 드론 택배함에 대해조사한 자료

1. 특허 : 여기서 참고할만한 기술 알아두기

-  스마트 명판을 이용한 배달물품 서비스 시스템 (등록)
도로 명 주소가 기재된 명판(건물번호판, 도로명판, 도로 명 주소 싸이니지)에 정보 인식 모듈을 부여한 스마트 명판 - 수취인(세대주, 세입자)과 서비스자(배달물품 기사, 집배원)가 스마트 명판을 통해 배달물품 데이터를 공유

- 드론 배달 택배 우체통 (거절)
제작된 사각통 하단 중앙에 무선송수신장치 및 센서을 위치하여 드론착륙을 유도, GPS을 통해 드론통의 주소를 추적, 블루투스를 통해 접근유도를 시키며 드론식별번호(카메라 인식용)를 통해 드론카메라에 식별시키므로써 안전한 착륙유도. 드론방문회수센서을 통해 드론도착알림과 확인을 소비자와 판매자에게 전달하는 시스템으로 구성.

- 3D 공간 좌표를 이용한 무인 드론 배달 서비스 제공 방법 (등록)
주소에 포함된 층수로부터 기 설정된 층수별 높이를 추출하여 무인 드론의 높이 좌표를 비교하는 단계, 비교 결과 무인 드론이 주소의 GPS 좌표에 위치한 경우, 무인 드론의 전동 로프를 이용하여 층수별 높이까지 컨테이너를 위치시키는 단계, 및 무인 드론으로부터 물품의 무게만큼 감소된 무게가 감지되는 경우, 사용자 단말로의 물품 배송을 완료하는 단계


2. ppt 마인드맵에 추가로 생각해볼 것
- 드론이 어떻게 주소를 찾는지 : 드론에 위치공유 후 정확한 드론이 왔는지 검토할 수 있는 시스템 필요(상품코드 등) : 맞을경우 받고, 틀릴경우 돌려보내는 시스템까지 / 회수 시스템 / 층수감별
- 개폐조절부분 : 눈이 얼어서 개폐가 용이하지 않을 수 있다면 앞으로 여는 방법은? 위의 모양은 그대로 유지, 앞으로 열린 후 버스 휠체어 발판? 같이 무언가 나와서 가지고 들어감
- 무게 : 난간이 견딜 수 있는 무게를 넘는 택배는? : 드론으로는 10kg도 배송 가능 https://tv.naver.com/v/3784567 (10kg를 들고 왕복 20km 가능한 드론)

3. 문제점
- 아직까지는 우리나라에서 드론 배달이 상용화 되지 않았음. 앞으로 드론 배달의 상용화까지 얼마나 걸릴지 모르는데 현 사회문제가 아닌 것에 대한 개발이 심사위원들의 이목을 끌 수 있을까? 우리나라가 아닌 미국등에 어울리는 것이 아닌가? : 주변인들에게 물어봤을 때 많이 나온 얘기
- 개인적으로 사비를 들여 택배함을 설치할만한 인구가 얼마나 될까? 수익을 낼 수 있는 만큼의 인원이 되는가?



이외
1. 병원에서 약국으로 바로 처방전을 전송하는 시스템 : 너무 쉬울수도?
2. 오프라인 회의에는 모두 노트북/태블릿등 들고 나오기. 바로 자료 찾아보며 공유할 수 있도록
