### ISSUE TITLE
after meeting review 2021.03.26 금 

### ISSUE THREAD

**Issue by sejun09** [sejun09/E-oN#9]
이전 3가지 아이디어 조사 결과 현재 비슷한 시스템이 많다. . .

### 새로 나온 아이디어 

- 시각장애인분들을 위한 터치스크린 도움 시스템
- 스쿨존 및 횡단보도 관련 시스템 
  1. 불법 주정차 
  2. 속도를 지키지 않는다. 
  3. 안전한 횡단보도 
----
### 교수님께 받은 feed back

1. 스마트 횡단보도 
생각해 볼 문제점 
- 교통 흐름에 방해되지 않게 유기적으로 신호를 바꾸는 부분에 대한 해결은 어렵다. 
- 스마트 횡단보도는 시간을 늘리는 결정을 언제 할 것인지. 만약 신호등이 깜빡이고 있는   중간에 노약자가 횡단을 시도한다면?

생각 
- 먼저 스마트 횡단보도 시스템은 교통에 흐름에 최대한 방해가 되지 않게 스쿨존 및 작은 골목길을 위주로 설치를 하는 방향으로 생각하고 있습니다!
- 횡단보도는 카메라로 인식해서 횡단 중 시간이 부족한 경우에는 시간을 늘려주지만, 신호가 깜빡이는 상황에서 횡단을 시도하면 무단횡단과 마찬가지로 음성으로 안내를 하는 방법

2. 스쿨존 불법주차 
생각해 볼 문제점
- 스쿨존 불법주차 단속은 지금 스마트폰 앱으로 있는 생활불편신고 앱을 이용한 불법주차 신고와 차이점이 무엇인지?
- 스쿨존 불법주차 단속은 지금 스쿨존마다 CCTV 설치되어 있어서 자동 단속 한다. 차이점이 뭔지?

----
### 교수님께서 스마트 횡단보도로 필요한 기능들을 정리해 보라고 하셨습니다!
ex)
1. 사람이 없을 때 보행신호는 켜지지 않는다.
2. 노약자가 있을 때 보행신호의 시간을 늘린다.
3. 깜빡일 때 횡단 시도할 경우 어떻게 메시지 띄울지?
4.
5.
6.
 등등...

대략적인 스마트 횡단보도 기능들 

- 횡단보도 구역 전체의 시야를 볼 수 있는 카메라를 설치 
- 횡단보도에 노약자 및 거동이 불편한 장애인들에게는 일반인을 대상으로 한 횡단시간이 짧을 수 있다. 따라서 카메라를 통해 자 
  동으로 보행자가 있을 경우 5~10초를 추가하여 횡단가능 시간을 늘려준다. 
- 카메라를 통해 적색 신호일 때 무단횡단을 시도하려는 움직임을 감지 시 음성으로 무단횡단을 주의시키는 안내를 한다. 

내일 (03/27 까지 스마트 횡단보도 관련하여 조사해서 카톡방에 올려주세요!!)

**Comment by fora22** [comment]
열심히 하고 계셔서 보기 좋네요. 힘드실텐데 조금 더 여유를 가지시기 바랍니다.

# 관련 내용에 관한 첨언

내용을 살펴보니 보행자 위주의 아이디어가 많습니다. 이번에는 운전자 입장에서의 아이디어도 하나 말씀드릴려 합니다.

이전부터 생각하던 것인데 운전자 입장에서 우회전할 때 신경써야 할 것이 많습니다. 왼쪽에서 오는 차량과 횡단보도를 건너려는 보행자도 신경 써야 하지요. 특히 횡단보도의 파란불이 들어오면 더욱 더 속도를 줄이고 신경이 쓰이게 됩니다. 

![image](https://user-images.githubusercontent.com/48875566/112610052-9ce19980-8e5f-11eb-9b06-1c262bd4224a.png)

하지만 운전자 입장에서 횡단보도의 불이 파란불인지 빨간불인지 인지하기 힘듭니다. 사진에서도 아마 파란불일겁니다.

운전자 입장에서는 사진처럼 횡단보도 신호등의 옆면이 보이기 때문이죠.

[동영상](https://youtu.be/YFkxE6_nSY4?t=94) 에서도 같은 문제점을 지적합니다. 그래서 동영상 끝에 별도로 표시하는 신호등을 추가 설치한다고 하는데, 운전자 입장에서는 저게 보행자용 신호등인지 운전자용 신호등인지 확인할려면 꽤나 힘이듭니다(개인 경험입니다. 여러분 중에 면허 있으신 분이 있을지 모르겠네요...). 

그래서 제 개인적인 생각에는 기존 횡단보도 신호등 위쪽에 새로운 모양의 심볼로 지금 파란불이다 라는 것을 보여주면 좋지 않을까 싶습니다.

[근거 1](https://youtu.be/jggOWwkIq8c)을 봐도 알 수 있듯이 우회전으로 인한 사고가 많은데요. 이런 식으로 스마트 횡단보도 기능에 하나를 추가하면 좋을 것 같아요.

**Comment by sejun09** [comment]
이 아이디어를 생각하면서 제가 차를 운전한 경험이 많지 않다보니 운전자의 시각을 생각하지 못했던거 같습니다..  의견 감사합니다!!
